[package]
name = "frontend"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
shared = { path = "../shared" }
chrono = "0.4"
yew = "0.19"
yew-router = "0.16"
yew-agent = "0.1"
yewdux = "0.8"
wasm-sockets = "0.2"
#keep in sync with yews gloo version
gloo = "0.4"
gloo-utils = "0.1"
gloo-storage = "0.2"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
serde = "1"
serde_json = "1"
anyhow = "1"
split-iter = "0.1"
wee_alloc = "0.4"
qrcode = "0.12"
# logging
log = "0.4"
wasm-logger = "0.2"

[dependencies.web-sys]
version = "0.3"
features = [
    "Clipboard",
    "Navigator",
    "Document",
    "Window",
    "DomRect",
    "CssStyleDeclaration",
    "ValidityState",
    "Request",
    "RequestInit",
    "RequestMode",
    "Response",
    "Headers",
    "DomTokenList"]

[dev-dependencies]
wasm-bindgen-test = "0.3.0"