# https://sagiegurari.github.io/cargo-make

[env]
RUSTFLAGS="--cfg=web_sys_unstable_apis"
# IS_PROD = "1"
# IS_BETA = "1"

[tasks.cargo-check]
command = "cargo"
args = ["c","--target=wasm32-unknown-unknown"]

[tasks.clippy]
install_crate = "clippy"
command = "cargo"
args = ["clippy","--target=wasm32-unknown-unknown","--","-D","clippy::unwrap_used"]

[tasks.test]
command = "cargo"
args = ["test","--target=wasm32-unknown-unknown"]

[tasks.format]
install_crate = "fmt"
command = "cargo"
args = ["fmt","--","--check"]

[tasks.la-check]
dependencies = ["format","cargo-check","clippy"]

[tasks.serve]
install_crate = "trunk"
command = "trunk"
args = ["serve","--no-autoreload"]

[tasks.serve-release]
install_crate = "trunk"
command = "trunk"
args = ["serve","--release","--no-autoreload"]

[tasks.build-release]
install_crate = "trunk"
command = "trunk"
args = ["build","--release"]

[tasks.check-size]
script_runner = "@shell"
dependencies = ["build-release"]
script = '''
ls -lh dist/*.wasm
'''

[tasks.build-and-check]
dependencies = ["build-release","check-size"]