# https://sagiegurari.github.io/cargo-make

[env]
BASE_URL = "http://localhost:8080"
DDB_LOCAL = 1

[tasks.run]
command = "cargo"
args = ["r"]

[tasks.format]
install_crate = "fmt"
command = "cargo"
args = ["fmt","--","--check"]

[tasks.cargo-sort]
install_crate = "cargo-sort"
command = "cargo"
args = ["sort","-c"]

[tasks.tests]
command = "cargo"
args = ["t"]

[tasks.clippy]
command = "cargo"
args = ["clippy","--",
	"-D","warnings",
	"-D","unused_imports",
	"-D","unused_must_use",
	"-D","unused_variables",
	"-D","unused_mut",
	"-D","dead_code",
	"-D","clippy::all",
	"-D","clippy::pedantic",
	"-D","clippy::dbg_macro",
	"-D","clippy::unwrap_used",
	"-D","clippy::panic",
	"-D","clippy::needless_update",
	"-D","clippy::match_like_matches_macro",
	"-D","clippy::from_over_into",
	"-D","clippy::useless_conversion",
	"-D","clippy::float_cmp_const",
	"-D","clippy::lossy_float_literal",
	"-D","clippy::string_to_string",
	"-D","clippy::unneeded_field_pattern",
	"-D","clippy::verbose_file_reads",
	"-A","clippy::module-name-repetitions"]

[tasks.checks]
dependencies = ["cargo-sort","format","clippy","tests"]

[tasks.run-release]
command = "cargo"
args = ["r","--release"]
