[package]
name = "backend_tests"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
shared = { path = "../shared" }
grillon = { version = "0.3.0", features = ["diff"] }
# grillon = { path="../../../extern/grillon" }
tokio = { version = "1", features = ["macros"] }
tungstenite = "0.16"
serde_json = "1"